Neos:
  EventSourcedContentRepository:
    testing:
      projectorsToBeReset:
        'Flowpack\ContentGraph\PostgreSQLAdapter\Domain\Projection\HypergraphProjector': true
    projection:
      defaultProjectorsToBeBlocked:
        'Flowpack\ContentGraph\PostgreSQLAdapter\Domain\Projection\HypergraphProjector': true
